### PR TITLE
Update 500 and Maintenance pages

### PR DESCRIPTION
**Pull request by cframe-itison**
## The Problem

The 500 and Maintenance pages for Hub are completely out of date compared to the new look and feel of Hub.
## The Solution

Use the Devise layouts from new Hub as a basis for the new 500 and Maintenance pages.

### CODE REVIEW

**Comment by johnd-itison** [comment]
These all look good (as far as DevOps/nginx path-type stuff is concerned), but I'm going to hold off on merging until Monday, since merging this will cause a production change - it'll download the new version automatically - and it's getting a bit late on a Friday for that.

**Comment by cframe-itison** [comment]
@johnd-itison are the 500 pages for hub now managed entirely via chef/nginx? It's been so long I've forgotten how Hub was configured!

**Comment by johnd-itison** [comment]
Yes - chef basically downloads this repo and drops the files on the LB for nginx to refer to.

The repo is set here: ```https://github.com/itison/itison-hub-cookbook/blob/master/recipes/loadbalancer.rb#L6```

And deployed using this code: ```https://github.com/itison/itison-loadbalancer/blob/master/recipes/nginx.rb#L69-L87```

**Comment by cframe-itison** [comment]
Closing this as it looks like the changes were made in a subsequent commit https://github.com/itison/hub-500-page/commit/a781c2328a9a8f46df9df6b0a340c960c480e493.

**Pull request closed without merging**
